stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - docker build -t cicd_mini_project .

test-job:
  stage: test
  script:
    - docker run --rm cicd_mini_project pytest -s -v

deploy-job:
  stage: deploy
  script:
    - docker compose up -d